rahaleht/budgets/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, HiddenField, DecimalField, BooleanField, StringField
from wtforms.validators import DataRequired, ValidationError, Length
from rahaleht.main.utils import get_lang, default_lang
from rahaleht.expenses.forms import DateForm
from rahaleht.models import Budget
from datetime import datetime, timezone, timedelta
from flask_login import current_user


lang = current_user.language if current_user else default_lang
time = datetime.now(timezone.utc) + timedelta(hours=2)
year_number = time.year

class BudgetForm(FlaskForm):
    def __init__(self, lang):
        super(BudgetForm, self).__init__(lang)
        self.save.label.text = get_lang(lang, "edit_expense", "save")
        self.name.default = get_lang(lang, "budgets", "default_name")
        self.salary.default = 0
        self.tuition.default = 0
        self.other_incomes.default = 0
        self.rent.default = 0
        self.utilities.default = 0
        self.groceries.default = 0
        self.transport.default = 0
        self.other_living_costs.default = 0
        self.clothing.default = 0
        self.entertainment.default = 0
        self.other_personal_expenses.default = 0
        self.stocks.default = 0
        self.fonds.default = 0
        self.bonds.default = 0
        self.savings.default = 0
        self.other_investments.default = 0
        
    name = StringField('', validators=[DataRequired(), Length(2, 30)])
    default = BooleanField('')
    month = HiddenField('', validators=[DataRequired()])
    year = HiddenField('', validators=[DataRequired()])
    salary = DecimalField('')
    tuition = DecimalField('')
    other_incomes = DecimalField('')
    rent = DecimalField('')
    utilities = DecimalField('')
    groceries = DecimalField('')
    transport = DecimalField('')
    other_living_costs = DecimalField('')
    clothing = DecimalField('')
    entertainment = DecimalField('')
    other_personal_expenses = DecimalField('')
    stocks = DecimalField('')
    bonds = DecimalField('')
    fonds = DecimalField('')
    savings = DecimalField('')
    other_investments = DecimalField('')
    save = SubmitField('')

    def validate_name(self, name):
        print(name.data, get_lang(lang, "budgets", "default_name"))
        if name.data == get_lang(lang, "budgets", "default_name"):
            raise ValidationError(get_lang(lang, "errors", "This field is required."))
        


class EditBudgetForm(BudgetForm):
    def __init__(self, lang):
        super(EditBudgetForm, self).__init__(lang)
        self.delete.label.text = get_lang(lang, "edit_expense", "delete")
    delete = SubmitField("")

rahaleht/budgets/routes.py
from flask import render_template, Blueprint, redirect, url_for, flash, request
from rahaleht.expenses.utils import get_categories
from rahaleht.budgets.forms import BudgetForm, EditBudgetForm
from rahaleht.expenses.forms import DateForm
from rahaleht.models import Budget
from rahaleht import db
from flask_login import current_user, login_required
from rahaleht.main.utils import get_lang
from datetime import datetime, timezone, timedelta

budgets = Blueprint('budgets', __name__)


@budgets.route("/budgets", methods=['POST', 'GET'])
@login_required
def budgets_overview():
    form = DateForm(current_user.language)
    return render_template('budgets.html', 
                           get_lang=get_lang, 
                           lang=current_user.language,
                           form=form, current_user=current_user)


@budgets.route("/new-budget/<year>/<month>", methods=['POST', 'GET'])
@login_required
def new_budget(year, month):
    form = BudgetForm(current_user.language)
    form.process(request.form)
    cat, subcat = get_categories()
    if request.method == 'GET':
        form.year.data = year
        form.month.data = int(month)
    if form.validate_on_submit():
        incomes = [form.salary.data, form.tuition.data, form.other_incomes.data]
        expenses = [form.rent.data, form.utilities.data, form.groceries.data, form.transport.data, 
                    form.other_living_costs.data, form.clothing.data, form.entertainment.data, 
                    form.other_personal_expenses.data, form.stocks.data, form.bonds.data, form.fonds.data, 
                    form.savings.data, form.other_investments.data]
        if form.default.data == 1:
            previous_default = Budget.query.filter_by(default=1).first()
            if previous_default:
                previous_default.default = 0
                db.session.commit()
        if sum(float(i or 0) for i in incomes) != sum(float(e or 0) for e in expenses):
            flash(get_lang(current_user.language, "errors", "budget_balance"), 'danger')
            return render_template('new_budget.html', get_lang=get_lang, form=form, 
                           lang=current_user.language, categories=cat, subcategories=subcat)
        elif sum(float(i or 0) for i in incomes) == 0:
            flash(get_lang(current_user.language, "errors", "budget_zero"), 'danger')
            return render_template('new_budget.html', get_lang=get_lang, form=form, 
                           lang=current_user.language, categories=cat, subcategories=subcat)
        else:
            budget = Budget(name=form.name.data, 
                            user_id=current_user.id,
                            month=form.month.data,
                            year=form.year.data, 
                            default=form.default.data, 
                            salary=form.salary.data, 
                            tuition=form.tuition.data, 
                            other_incomes=form.other_incomes.data, 
                            rent=form.rent.data, 
                            utilities=form.utilities.data, 
                            groceries=form.groceries.data, 
                            transport=form.transport.data, 
                            other_living_costs=form.other_living_costs.data, 
                            clothing=form.clothing.data, 
                            entertainment=form.entertainment.data, 
                            other_personal_expenses=form.other_personal_expenses.data, 
                            stocks=form.stocks.data, 
                            bonds=form.bonds.data, 
                            fonds=form.fonds.data, 
                            savings=form.savings.data, 
                            other_investments=form.other_investments.data)
            db.session.add(budget)
            db.session.commit()
            flash(get_lang(current_user.language, "budgets", "budget_created"), 'success')
            return redirect(url_for('budgets.budgets_overview'))
    return render_template('new_budget.html', get_lang=get_lang, form=form, 
                           lang=current_user.language, categories=cat, subcategories=subcat)

@budgets.route("/edit-budget/<budget_id>", methods=['POST', 'GET'])
@login_required
def edit_budget(budget_id):
    cat, subcat = get_categories()
    budget = Budget.query.filter_by(id=budget_id, user_id=current_user.id).first()
    form = EditBudgetForm(current_user.language)
    form.process(request.form)
    cat, subcat = get_categories()
    if request.method == 'GET':
        form.name.data = budget.name
        form.year.data = budget.year
        form.month.data = budget.month
        form.default.data = budget.default
        form.salary.data = budget.salary
        form.tuition.data = budget.tuition
        form.other_incomes.data = budget.other_incomes
        form.rent.data = budget.rent
        form.utilities.data = budget.utilities
        form.groceries.data = budget.groceries
        form.transport.data = budget.transport
        form.other_living_costs.data = budget.other_living_costs
        form.clothing.data = budget.clothing
        form.entertainment.data = budget.entertainment
        form.other_personal_expenses.data = budget.other_personal_expenses
        form.stocks.data = budget.stocks
        form.fonds.data = budget.fonds
        form.bonds.data = budget.bonds
        form.savings.data = budget.savings
        form.other_investments.data = budget.other_investments
    if form.delete.data:
        print("siin")
        db.session.delete(budget)
        db.session.commit()
        flash(get_lang(current_user.language, "budget", "budget_deleted"))
        return redirect(url_for('budgets.budgets_overview')) 
    elif form.validate_on_submit():
        incomes = [form.salary.data, form.tuition.data, form.other_incomes.data]
        expenses = [form.rent.data, form.utilities.data, form.groceries.data, form.transport.data, 
                    form.other_living_costs.data, form.clothing.data, form.entertainment.data, 
                    form.other_personal_expenses.data, form.stocks.data, form.bonds.data, form.fonds.data, 
                    form.savings.data, form.other_investments.data]
        if form.default.data == 1:
            previous_default = Budget.query.filter_by(default=1).first()
            if previous_default:
                previous_default.default = 0
                db.session.commit()
        if sum(float(i or 0) for i in incomes) != sum(float(e or 0) for e in expenses):
            flash(get_lang(current_user.language, "errors", "budget_balance"), 'danger')
            return render_template('new_budget.html', get_lang=get_lang, form=form, 
                           lang=current_user.language, categories=cat, subcategories=subcat)
        elif sum(float(i or 0) for i in incomes) == 0:
            flash(get_lang(current_user.language, "errors", "budget_zero"), 'danger')
            return render_template('new_budget.html', get_lang=get_lang, form=form, 
                           lang=current_user.language, categories=cat, subcategories=subcat)
        else:
            budget.name = form.name.data
            budget.default = form.default.data
            budget.salary = form.salary.data
            budget.tuition = form.tuition.data
            budget.other_incomes = form.other_incomes.data
            budget.rent = form.rent.data
            budget.utilities = form.utilities.data
            budget.groceries = form.groceries.data
            budget.transport = form.transport.data
            budget.other_living_costs = form.other_living_costs.data
            budget.clothing = form.clothing.data
            budget.entertainment = form.entertainment.data
            budget.other_personal_expenses = form.other_personal_expenses.data
            budget.stocks = form.stocks.data
            budget.bonds = form.bonds.data
            budget.fonds = form.fonds.data
            budget.savings = form.savings.data
            budget.other_investments = form.other_investments.data
            db.session.commit()
            flash(get_lang(current_user.language, "budgets", "budget_updated"), 'success')
            return redirect(url_for('budgets.budgets_overview'))

    return render_template('edit_budget.html', get_lang=get_lang, form=form, 
                           lang=current_user.language, categories=cat, subcategories=subcat)

rahaleht/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from rahaleht.models import User
from rahaleht.users.forms import loginForm, registrationForm, settingsForm, RequestResetForm, ResetPasswordForm
from rahaleht import db, bcrypt
from rahaleht.users.utils import save_picture, delete_picture, send_reset_email
from rahaleht.main.utils import get_lang, default_lang	
from flask_login import login_user, current_user, logout_user, login_required


users = Blueprint('users', __name__)

@users.route("/register", methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('expenses.overview'))
    form = registrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password=hashed_pw, email=form.email.data)
        db.session.add(user)
        db.session.commit()
        flash(f'{get_lang(default_lang, 'register', 'account_created')} {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form, current_path=request.path, get_lang=get_lang, lang=default_lang)


@users.route("/login", methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('expenses.overview'))
    form = loginForm()
    if form.validate_on_submit():
        user_by_username = User.query.filter_by(username=form.user_input.data).first()
        user_by_email = User.query.filter_by(email=form.user_input.data).first()
        if user_by_username and bcrypt.check_password_hash(user_by_username.password, form.password.data):
            login_user(user_by_username, remember=form.remember.data)
            return redirect(url_for('expenses.overview'))
        elif user_by_email and bcrypt.check_password_hash(user_by_email.password, form.password.data):
            login_user(user_by_email, remember=form.remember.data)
            return redirect(url_for('expenses.overview'))
        else:
            flash(get_lang(default_lang, 'login', 'unsuccesful'), 'danger')
    return render_template('login.html', title='Log in', form=form, current_path=request.path, get_lang=get_lang, lang=default_lang)


@users.route("/logout", methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route("/settings", methods=['POST', 'GET'])
@login_required
def settings():
    img_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    form = settingsForm(current_user.language)
    flash_message = False
    if form.validate_on_submit():
        if (form.default_picture.data and current_user.image_file != 'default.jpg') or \
            form.picture.data or (current_user.email != form.email.data) or \
            (current_user.username != form.username.data) or \
            (current_user.language != form.language.data):
            flash_message = True
        if form.picture.data:
            delete_picture(current_user.image_file)
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        elif form.default_picture.data:
            delete_picture(current_user.image_file)
            current_user.image_file = 'default.jpg'
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.language = form.language.data
        db.session.commit()
        if flash_message:
            flash(get_lang(current_user.language, "settings", "changes_saved"), 'success')
        return redirect(url_for('users.settings'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.language.data = current_user.language
    return render_template('settings.html', current_path=request.path, 
                           img_file=img_file, form=form, lang=current_user.language, 
                           get_lang=get_lang)


@users.route("/reset_password", methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('expenses.overview'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(get_lang(default_lang, "reset_token", "email_sent"), 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form, lang=default_lang, get_lang=get_lang)


@users.route("/reset_password/<token>", methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('expenses.overview'))
    user = User.verify_reset_token(token)
    if user is None:
        flash(f'Token not valid', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash(get_lang(default_lang, "reset_token", "reset_done"), 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form, lang=default_lang, get_lang=get_lang)

rahaleht/templates/budgets.html
{% extends "layout.html" %}
{% block sisu %}
     <div class="items-column" id="budgets">
        <div class="bg-gray" id="budgets-overview">
            <input type="hidden" id="current-user-id" value="{{ current_user.id }}">
            <input type="hidden" id="budget-default" value="{{ get_lang(lang, 'budgets', 'is_default') }}">
            <div id="data-url" data-edit-url="{{ url_for('budgets.edit_budget', budget_id='') }}"></div>
            <div class="page-top" id="budgets-page-top">
                <legend class="account-form-legend text text-l" id="budget-legend"></legend>
                <legend class="account-form-legend text text-l" id="budget-legend-default">{{ get_lang(lang, "budgets", "budget_legend") }}</legend>
            </div>
            <div id="budget-info">
                <div id="name-buttons">
                    <div class="budget-name-container name-close" id="add-budget">
                        <a href="{{ url_for('budgets.new_budget', year='', month='') }}" class="text text-s form-text" id="budget-default-name">{{ get_lang(lang, "budgets", "add_budget") }}</a>
                    </div>
                    <div class="budget-name-container name-close" id="budget-edit">
                        <a href="{{ url_for('budgets.edit_budget', budget_id='') }}" class="text text-s form-text" id="edit-link">{{ get_lang(lang, "budgets", "edit_budget") }}</a>
                    </div>
                </div>
                <div class="time-select">
                    {{ form.month(class="text text-s form-text bg-white form-field", id="month-select") }}
                    {{ form.year(class="text text-s form-text bg-white form-field", id="year-select") }}
                </div>
            </div>
            <div id="budget-container">
                <div id="total-incomes-container">
                    <div class="cat-container" id="incomes-div">
                        <div class="cat-head bg-white" id="incomes-head">
                            <h2 class="text text-m form-text">{{ get_lang(lang, "incomes", "cat_name") }}</h2>
                            <p class="text text-m form-text cat-closed" id="incomes">0</p>
                        </div>
                        <div class="subcat-container edit-cat" id="incomes-container">
                            <div class="subcat-name">
                                <h3 class="text text-s text-bold">{{ get_lang(lang, "overview", "total") }}</h3>
                                <p class="text text-s text-bold" id="incomes-total">0 €</p>
                            </div>
                        </div>
                    </div>
                    <div id="budget-conclusion">
                        <div>
                            <div class="subcat-name">
                                <h2 class="text text-m text-bold">{{ get_lang(lang, "overview", "total_incomes") }}</h2>
                                <p class="text text-m text-bold" id="total-incomes">0 €</p>
                            </div>
                        </div>
                        <div>
                            <div class="subcat-name">
                                <h2 class="text text-m text-bold">{{ get_lang(lang, "overview", "total_expenses") }}</h2>
                                <p class="text text-m text-bold" id="total-expenses">0 €</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="expenses-container">
                    <div class="cat-container" id="living-costs-div">
                        <div class="cat-head bg-white" id="living-costs-head">
                            <h2 class="text text-m form-text">{{ get_lang(lang, "living_costs", "cat_name") }}</h2>
                            <p class="text text-m form-text cat-closed" id="living-costs">0</p>
                        </div>
                        <div class="subcat-container edit-cat" id="living-costs-container">
                            <div class="subcat-name">
                                <h3 class="text text-s text-bold">{{ get_lang(lang, "overview", "total") }}</h3>
                                <p class="text text-s text-bold" id="living-costs-total">0 €</p>
                            </div>
                        </div>
                    </div>
                    <div class="cat-container" id="personal-expenses-div">
                        <div class="cat-head bg-white" id="personal-expenses-head">
                            <h2 class="text text-m form-text">{{ get_lang(lang, "personal_expenses", "cat_name") }}</h2>
                            <p class="text text-m form-text cat-closed" id="personal-expenses">0</p>
                        </div>
                        <div class="subcat-container edit-cat" id="personal-expenses-container">
                            <div class="subcat-name">
                                <h3 class="text text-s text-bold">{{ get_lang(lang, "overview", "total") }}</h3>
                                <p class="text text-s text-bold" id="personal-expenses-total">0 €</p>
                            </div>
                        </div>
                    </div>
                    <div class="cat-container" id="investing-div">
                        <div class="cat-head bg-white" id="investing-head">
                            <h2 class="text text-m form-text">{{ get_lang(lang, "investing", "cat_name") }}</h2>
                            <p class="text text-m form-text cat-closed" id="investing">0 €</p>
                        </div>
                        <div class="subcat-container edit-cat" id="investing-container">
                            <div class="subcat-name">
                                <h3 class="text text-s text-bold">{{ get_lang(lang, "overview", "total") }}</h3>
                                <p class="text text-s text-bold" id="investing-total">0 €</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
{% endblock sisu %}

rahaleht/templates/home.html
{% extends "layout.html" %}
{% block sisu %}
{% endblock sisu %}

rahaleht/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Rahaleht</title>
    {% endif %}

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='form.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='settings.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stats.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='budget.css') }}">
</head>
<body>
    <header class="p-header">
        <nav class="navb bg-gray">
            <ul class="nav-container left">
                <li id="home-id"><p class="text text-m"><span class="glyphicon glyphicon-menu-hamburger"></span></p></li>
            </ul>
            <ul class="nav-container right">
                {% if current_user.is_authenticated %}
                    <li class="{% if current_path == url_for('users.settings') %}active{% endif %}"><a class="text text-m" href="{{ url_for('users.settings') }}"><span class="glyphicon glyphicon-cog"></span></a></li>
                    <li><a class="text text-m" href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-log-out"></span></a></li>
                {% else %}
                    <li class="{% if current_path == url_for('users.register') %}active{% endif %}"><a class="text text-m" href="{{ url_for('users.register') }}"><span class="glyphicon glyphicon-user"></span></a></li>
                    <li class="{% if current_path == url_for('users.login') %}active{% endif %}"><a class="text text-m" href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span></a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="sidebar-container">
        <ul class="sidebar bg-dark">
            <li><a href="{{ url_for('expenses.overview') }}" class="text text-m">{{ get_lang(lang, "home", "overview") }}</a></li>
            <li><a href="{{ url_for('budgets.budgets_overview') }}" class="text text-m">{{ get_lang(lang, "home", "budget") }}</a></li>
        </ul>
    </div>
    <div class="content-container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {% if category == 'success' %}
                            <span class="text-xs glyphicon glyphicon-ok-circle"></span> <span class="font text-xs">{{ message }}</span>
                        {% elif category == 'danger' %}
                            <span class="text-xs glyphicon glyphicon-remove-circle"></span> <span class="font text-xs">{{ message }}</span>
                        {% elif category == 'info' %}
                            <span class="text-xs glyphicon glyphicon-info-sign"></span> <span class="font text-xs">{{ get_lang(lang, 'info', message) }}</span>
                        {% elif category == 'warning' %}
                            <span class="text-xs glyphicon glyphicon-warning-sign"></span> <span class="font text-xs">{{ message }}</span>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block sisu %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='main.js') }}"></script>
    <script src="{{ url_for('static', filename='expense.js') }}"></script>
    <script src="{{ url_for('static', filename='data_fetch.js') }}"></script>
    <script src="{{ url_for('static', filename='budget.js') }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

rahaleht/templates/login.html
{% extends "layout.html" %}
{% block sisu %}
    <div class="form-container bg-gray">
        <form method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="form-legend text text-l">{{ get_lang(lang, "login", "login") }}</legend>
                <div class="form-pair">
                    <p class="text text-s">{{ get_lang(lang, "login", "email") }}</p>
                    {% if form.user_input.errors %}
                        {{ form.user_input(class="text text-s form-text invalid-div") }}
                        {% for error in form.user_input.errors %}
                            <div>
                                <span class="error-text text text-xxs">{{ get_lang(lang, "errors", error) }}</span>
                            </div>
                        {% endfor %}
                    {% else %}
                        {{ form.user_input(class="text text-s form-field form-text") }}
                    {% endif %}
                </div>
                <div class="form-pair">
                    <p class="text text-s">{{ get_lang(lang, "login", "password") }}</p>
                    {% if form.password.errors %}
                        {{ form.password(class="text text-s form-text invalid-div") }}
                        {% for error in form.password.errors %}
                            <div>
                                <span class="error-text text text-xxs">{{ get_lang(lang, "errors", error) }}</span>
                            </div>
                        {% endfor %}
                    {% else %}
                        {{ form.password(class="text text-s form-field form-text") }}
                    {% endif %}
                </div>
                <div class="login-div">
                    <div>
                        <div class="form-check">
                            {{ form.remember(class="form-check-input") }}
                            <p class="text text-xxs">{{ get_lang(lang, "login", "remember") }}</p>
                        </div>
                    </div>
                    <div class="forgot-password">
                        <p class="text text-xxs">{{ get_lang(lang, "login", "forgot") }} <a href="{{ url_for('users.reset_request') }}" class="text text-xxs">{{ get_lang(lang, "login", "click") }}</a></p>
                    </div>
                </div>
            </fieldset>
            <div class="form-pair">
                {{ form.submit(class="submit-btn text text-s") }}
            </div>
            <div class="link-div">
                <p class="text text-xs">{{ get_lang(lang, "login", "or") }} <a href="{{ url_for('users.register') }}" class="text text-xs">{{ get_lang(lang, "login", "register") }}</a></p>
            </div>
    </div>
{% endblock sisu %}

rahaleht/templates/reset_request.html
{% extends "layout.html" %}
{% block sisu %}
    <div class="form-container bg-gray">
        <form method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="form-legend text text-l">{{ get_lang(lang, "reset_request", "reset_pw") }}</legend>
                <div class="form-pair">
                    {{ form.email.label(class="text text-s") }}
                    {% if form.email.errors %}
                        {{ form.email(class="text text-s form-text invalid-div form-field") }}
                        {% for error in form.email.errors %}
                            <div>
                                <span class="error-text text text-xxs">{{ get_lang(lang, "errors", error) }}</span>
                            </div>
                        {% endfor %}
                    {% else %}
                        {{ form.email(class="text text-s form-text form-field") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-pair">
                {{ form.submit(class="submit-btn text text-s") }}
            </div>
    </div>
{% endblock sisu %}